package swim.recolor;

public class DefaultFiles {

    public static String[] getDefaultFileNameArray() {
        String[] defaults = {"diamond_sword",
                "diamond_shovel",
                "diamond_pickaxe",
                "diamond_leggings",
                "diamond_horse_armor",
                "diamond_hoe",
                "diamond_chestplate",
                "diamond_helmet",
                "diamond_boots",
                "diamond_axe",
                "diamond",
                "diamond_ore",
                "diamond_block",
                "apple",
                "apple_golden",
                "bed",
                "icons",
                "widgets",
                "cubemap_0",
                "cubemap_1",
                "cubemap_2",
                "cubemap_3",
                "cubemap_4",
                "cubemap_5",
                "sky",
                "cloud1",
                "inventory",
                "gui",
                "hotdogempty",
                "hotdogfull",
                "diamond_1",
                "diamond_2",
                "experiencebarfull",
                "filled_progress_bar",
                "empty_progress_bar",
                "diamond_layer_1",
                "diamond_layer_2",
                "diamond_1",
                "diamond_2",
                "ender_pearl",
                "bow",
                "bow_pulling_0",
                "bow_pulling_1",
                "bow_pulling_2",
                "bow_standby",
                "totem",
                "generic_54",
                "pack_icon",
                "pack",
                "bed",
                "beacon",
                "bed_feet_end",
                "bed_feet_side",
                "bed_feet_top",
                "bed_head_end",
                "bed_head_side",
                "bed_head_top"};
        return defaults;
    }
}
